/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.sanlo.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FinancialReport extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -83422930235469094L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FinancialReport\",\"namespace\":\"io.sanlo.avro.model\",\"fields\":[{\"name\":\"companyId\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"companyName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"appName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"riskScore\",\"type\":\"int\"},{\"name\":\"riskRating\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"aggregatedRevenues\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"aggregatedMarketingSpent\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"date\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"paybackDate\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FinancialReport> ENCODER =
      new BinaryMessageEncoder<FinancialReport>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FinancialReport> DECODER =
      new BinaryMessageDecoder<FinancialReport>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<FinancialReport> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<FinancialReport> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FinancialReport>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this FinancialReport to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a FinancialReport from a ByteBuffer. */
  public static FinancialReport fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer companyId;
  @Deprecated public java.lang.CharSequence companyName;
  @Deprecated public java.lang.CharSequence appName;
  @Deprecated public int riskScore;
  @Deprecated public java.lang.CharSequence riskRating;
  @Deprecated public java.lang.Double aggregatedRevenues;
  @Deprecated public java.lang.Double aggregatedMarketingSpent;
  @Deprecated public java.lang.CharSequence date;
  @Deprecated public java.lang.CharSequence paybackDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FinancialReport() {}

  /**
   * All-args constructor.
   * @param companyId The new value for companyId
   * @param companyName The new value for companyName
   * @param appName The new value for appName
   * @param riskScore The new value for riskScore
   * @param riskRating The new value for riskRating
   * @param aggregatedRevenues The new value for aggregatedRevenues
   * @param aggregatedMarketingSpent The new value for aggregatedMarketingSpent
   * @param date The new value for date
   * @param paybackDate The new value for paybackDate
   */
  public FinancialReport(java.lang.Integer companyId, java.lang.CharSequence companyName, java.lang.CharSequence appName, java.lang.Integer riskScore, java.lang.CharSequence riskRating, java.lang.Double aggregatedRevenues, java.lang.Double aggregatedMarketingSpent, java.lang.CharSequence date, java.lang.CharSequence paybackDate) {
    this.companyId = companyId;
    this.companyName = companyName;
    this.appName = appName;
    this.riskScore = riskScore;
    this.riskRating = riskRating;
    this.aggregatedRevenues = aggregatedRevenues;
    this.aggregatedMarketingSpent = aggregatedMarketingSpent;
    this.date = date;
    this.paybackDate = paybackDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return companyId;
    case 1: return companyName;
    case 2: return appName;
    case 3: return riskScore;
    case 4: return riskRating;
    case 5: return aggregatedRevenues;
    case 6: return aggregatedMarketingSpent;
    case 7: return date;
    case 8: return paybackDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: companyId = (java.lang.Integer)value$; break;
    case 1: companyName = (java.lang.CharSequence)value$; break;
    case 2: appName = (java.lang.CharSequence)value$; break;
    case 3: riskScore = (java.lang.Integer)value$; break;
    case 4: riskRating = (java.lang.CharSequence)value$; break;
    case 5: aggregatedRevenues = (java.lang.Double)value$; break;
    case 6: aggregatedMarketingSpent = (java.lang.Double)value$; break;
    case 7: date = (java.lang.CharSequence)value$; break;
    case 8: paybackDate = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return The value of the 'companyId' field.
   */
  public java.lang.Integer getCompanyId() {
    return companyId;
  }

  /**
   * Sets the value of the 'companyId' field.
   * @param value the value to set.
   */
  public void setCompanyId(java.lang.Integer value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'companyName' field.
   * @return The value of the 'companyName' field.
   */
  public java.lang.CharSequence getCompanyName() {
    return companyName;
  }

  /**
   * Sets the value of the 'companyName' field.
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.CharSequence value) {
    this.companyName = value;
  }

  /**
   * Gets the value of the 'appName' field.
   * @return The value of the 'appName' field.
   */
  public java.lang.CharSequence getAppName() {
    return appName;
  }

  /**
   * Sets the value of the 'appName' field.
   * @param value the value to set.
   */
  public void setAppName(java.lang.CharSequence value) {
    this.appName = value;
  }

  /**
   * Gets the value of the 'riskScore' field.
   * @return The value of the 'riskScore' field.
   */
  public java.lang.Integer getRiskScore() {
    return riskScore;
  }

  /**
   * Sets the value of the 'riskScore' field.
   * @param value the value to set.
   */
  public void setRiskScore(java.lang.Integer value) {
    this.riskScore = value;
  }

  /**
   * Gets the value of the 'riskRating' field.
   * @return The value of the 'riskRating' field.
   */
  public java.lang.CharSequence getRiskRating() {
    return riskRating;
  }

  /**
   * Sets the value of the 'riskRating' field.
   * @param value the value to set.
   */
  public void setRiskRating(java.lang.CharSequence value) {
    this.riskRating = value;
  }

  /**
   * Gets the value of the 'aggregatedRevenues' field.
   * @return The value of the 'aggregatedRevenues' field.
   */
  public java.lang.Double getAggregatedRevenues() {
    return aggregatedRevenues;
  }

  /**
   * Sets the value of the 'aggregatedRevenues' field.
   * @param value the value to set.
   */
  public void setAggregatedRevenues(java.lang.Double value) {
    this.aggregatedRevenues = value;
  }

  /**
   * Gets the value of the 'aggregatedMarketingSpent' field.
   * @return The value of the 'aggregatedMarketingSpent' field.
   */
  public java.lang.Double getAggregatedMarketingSpent() {
    return aggregatedMarketingSpent;
  }

  /**
   * Sets the value of the 'aggregatedMarketingSpent' field.
   * @param value the value to set.
   */
  public void setAggregatedMarketingSpent(java.lang.Double value) {
    this.aggregatedMarketingSpent = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'paybackDate' field.
   * @return The value of the 'paybackDate' field.
   */
  public java.lang.CharSequence getPaybackDate() {
    return paybackDate;
  }

  /**
   * Sets the value of the 'paybackDate' field.
   * @param value the value to set.
   */
  public void setPaybackDate(java.lang.CharSequence value) {
    this.paybackDate = value;
  }

  /**
   * Creates a new FinancialReport RecordBuilder.
   * @return A new FinancialReport RecordBuilder
   */
  public static io.sanlo.avro.model.FinancialReport.Builder newBuilder() {
    return new io.sanlo.avro.model.FinancialReport.Builder();
  }

  /**
   * Creates a new FinancialReport RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FinancialReport RecordBuilder
   */
  public static io.sanlo.avro.model.FinancialReport.Builder newBuilder(io.sanlo.avro.model.FinancialReport.Builder other) {
    return new io.sanlo.avro.model.FinancialReport.Builder(other);
  }

  /**
   * Creates a new FinancialReport RecordBuilder by copying an existing FinancialReport instance.
   * @param other The existing instance to copy.
   * @return A new FinancialReport RecordBuilder
   */
  public static io.sanlo.avro.model.FinancialReport.Builder newBuilder(io.sanlo.avro.model.FinancialReport other) {
    return new io.sanlo.avro.model.FinancialReport.Builder(other);
  }

  /**
   * RecordBuilder for FinancialReport instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FinancialReport>
    implements org.apache.avro.data.RecordBuilder<FinancialReport> {

    private java.lang.Integer companyId;
    private java.lang.CharSequence companyName;
    private java.lang.CharSequence appName;
    private int riskScore;
    private java.lang.CharSequence riskRating;
    private java.lang.Double aggregatedRevenues;
    private java.lang.Double aggregatedMarketingSpent;
    private java.lang.CharSequence date;
    private java.lang.CharSequence paybackDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.sanlo.avro.model.FinancialReport.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.companyId)) {
        this.companyId = data().deepCopy(fields()[0].schema(), other.companyId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyName)) {
        this.companyName = data().deepCopy(fields()[1].schema(), other.companyName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.appName)) {
        this.appName = data().deepCopy(fields()[2].schema(), other.appName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.riskScore)) {
        this.riskScore = data().deepCopy(fields()[3].schema(), other.riskScore);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.riskRating)) {
        this.riskRating = data().deepCopy(fields()[4].schema(), other.riskRating);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.aggregatedRevenues)) {
        this.aggregatedRevenues = data().deepCopy(fields()[5].schema(), other.aggregatedRevenues);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.aggregatedMarketingSpent)) {
        this.aggregatedMarketingSpent = data().deepCopy(fields()[6].schema(), other.aggregatedMarketingSpent);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.date)) {
        this.date = data().deepCopy(fields()[7].schema(), other.date);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.paybackDate)) {
        this.paybackDate = data().deepCopy(fields()[8].schema(), other.paybackDate);
        fieldSetFlags()[8] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FinancialReport instance
     * @param other The existing instance to copy.
     */
    private Builder(io.sanlo.avro.model.FinancialReport other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.companyId)) {
        this.companyId = data().deepCopy(fields()[0].schema(), other.companyId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyName)) {
        this.companyName = data().deepCopy(fields()[1].schema(), other.companyName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.appName)) {
        this.appName = data().deepCopy(fields()[2].schema(), other.appName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.riskScore)) {
        this.riskScore = data().deepCopy(fields()[3].schema(), other.riskScore);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.riskRating)) {
        this.riskRating = data().deepCopy(fields()[4].schema(), other.riskRating);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.aggregatedRevenues)) {
        this.aggregatedRevenues = data().deepCopy(fields()[5].schema(), other.aggregatedRevenues);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.aggregatedMarketingSpent)) {
        this.aggregatedMarketingSpent = data().deepCopy(fields()[6].schema(), other.aggregatedMarketingSpent);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.date)) {
        this.date = data().deepCopy(fields()[7].schema(), other.date);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.paybackDate)) {
        this.paybackDate = data().deepCopy(fields()[8].schema(), other.paybackDate);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'companyId' field.
      * @return The value.
      */
    public java.lang.Integer getCompanyId() {
      return companyId;
    }

    /**
      * Sets the value of the 'companyId' field.
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setCompanyId(java.lang.Integer value) {
      validate(fields()[0], value);
      this.companyId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'companyId' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearCompanyId() {
      companyId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyName() {
      return companyName;
    }

    /**
      * Sets the value of the 'companyName' field.
      * @param value The value of 'companyName'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setCompanyName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.companyName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'companyName' field has been set.
      * @return True if the 'companyName' field has been set, false otherwise.
      */
    public boolean hasCompanyName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'companyName' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearCompanyName() {
      companyName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'appName' field.
      * @return The value.
      */
    public java.lang.CharSequence getAppName() {
      return appName;
    }

    /**
      * Sets the value of the 'appName' field.
      * @param value The value of 'appName'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setAppName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.appName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'appName' field has been set.
      * @return True if the 'appName' field has been set, false otherwise.
      */
    public boolean hasAppName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'appName' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearAppName() {
      appName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'riskScore' field.
      * @return The value.
      */
    public java.lang.Integer getRiskScore() {
      return riskScore;
    }

    /**
      * Sets the value of the 'riskScore' field.
      * @param value The value of 'riskScore'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setRiskScore(int value) {
      validate(fields()[3], value);
      this.riskScore = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'riskScore' field has been set.
      * @return True if the 'riskScore' field has been set, false otherwise.
      */
    public boolean hasRiskScore() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'riskScore' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearRiskScore() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'riskRating' field.
      * @return The value.
      */
    public java.lang.CharSequence getRiskRating() {
      return riskRating;
    }

    /**
      * Sets the value of the 'riskRating' field.
      * @param value The value of 'riskRating'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setRiskRating(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.riskRating = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'riskRating' field has been set.
      * @return True if the 'riskRating' field has been set, false otherwise.
      */
    public boolean hasRiskRating() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'riskRating' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearRiskRating() {
      riskRating = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregatedRevenues' field.
      * @return The value.
      */
    public java.lang.Double getAggregatedRevenues() {
      return aggregatedRevenues;
    }

    /**
      * Sets the value of the 'aggregatedRevenues' field.
      * @param value The value of 'aggregatedRevenues'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setAggregatedRevenues(java.lang.Double value) {
      validate(fields()[5], value);
      this.aggregatedRevenues = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregatedRevenues' field has been set.
      * @return True if the 'aggregatedRevenues' field has been set, false otherwise.
      */
    public boolean hasAggregatedRevenues() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'aggregatedRevenues' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearAggregatedRevenues() {
      aggregatedRevenues = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'aggregatedMarketingSpent' field.
      * @return The value.
      */
    public java.lang.Double getAggregatedMarketingSpent() {
      return aggregatedMarketingSpent;
    }

    /**
      * Sets the value of the 'aggregatedMarketingSpent' field.
      * @param value The value of 'aggregatedMarketingSpent'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setAggregatedMarketingSpent(java.lang.Double value) {
      validate(fields()[6], value);
      this.aggregatedMarketingSpent = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'aggregatedMarketingSpent' field has been set.
      * @return True if the 'aggregatedMarketingSpent' field has been set, false otherwise.
      */
    public boolean hasAggregatedMarketingSpent() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'aggregatedMarketingSpent' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearAggregatedMarketingSpent() {
      aggregatedMarketingSpent = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.CharSequence getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.date = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearDate() {
      date = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'paybackDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaybackDate() {
      return paybackDate;
    }

    /**
      * Sets the value of the 'paybackDate' field.
      * @param value The value of 'paybackDate'.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder setPaybackDate(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.paybackDate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'paybackDate' field has been set.
      * @return True if the 'paybackDate' field has been set, false otherwise.
      */
    public boolean hasPaybackDate() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'paybackDate' field.
      * @return This builder.
      */
    public io.sanlo.avro.model.FinancialReport.Builder clearPaybackDate() {
      paybackDate = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FinancialReport build() {
      try {
        FinancialReport record = new FinancialReport();
        record.companyId = fieldSetFlags()[0] ? this.companyId : (java.lang.Integer) defaultValue(fields()[0]);
        record.companyName = fieldSetFlags()[1] ? this.companyName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.appName = fieldSetFlags()[2] ? this.appName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.riskScore = fieldSetFlags()[3] ? this.riskScore : (java.lang.Integer) defaultValue(fields()[3]);
        record.riskRating = fieldSetFlags()[4] ? this.riskRating : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.aggregatedRevenues = fieldSetFlags()[5] ? this.aggregatedRevenues : (java.lang.Double) defaultValue(fields()[5]);
        record.aggregatedMarketingSpent = fieldSetFlags()[6] ? this.aggregatedMarketingSpent : (java.lang.Double) defaultValue(fields()[6]);
        record.date = fieldSetFlags()[7] ? this.date : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.paybackDate = fieldSetFlags()[8] ? this.paybackDate : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FinancialReport>
    WRITER$ = (org.apache.avro.io.DatumWriter<FinancialReport>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FinancialReport>
    READER$ = (org.apache.avro.io.DatumReader<FinancialReport>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
